import Head from 'next/head';
import styles from '../styles/Home.module.css';
import * as React from 'react';
import { useAccount } from 'wagmi';
import { Account, Connect, DAOModerators } from '../components';
import { useIsMounted } from '../hooks';

function Home() {
    const isMounted = useIsMounted();
    const { isConnected } = useAccount();

    return (
        <div className={styles.container}>
            <Head>
                <title>Quadratic voting DAO</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to quadratic voting DAO
                </h1>
                <>
                    <Connect />
                    <DAOModerators />

                    {isMounted && isConnected && ( <> <Account /> </> )}
                </>
            </main>
        </div>
    );
}

export default Home;